#!/bin/sh

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

[ -d /dev ] || mkdir -m 0755 /dev
[ -d /root ] || mkdir -m 0700 /root
[ -d /sys ] || mkdir /sys
[ -d /proc ] || mkdir /proc
[ -d /tmp ] || mkdir /tmp
mkdir -p /var/lock
mount -t sysfs -o nodev,noexec,nosuid sysfs /sys
mount -t proc -o nodev,noexec,nosuid proc /proc

mount -t devtmpfs -o nosuid,mode=0755 udev /dev

echo "Mount CDROM"
mkdir /cdrom

mount -t iso9660 /dev/sr0 /cdrom
mount -o loop /cdrom/live/simple_ubuntu_live.squashfs /root

mount -n -o move /dev /root/dev
mount -n -o move /sys /root/sys
mount -n -o move /proc /root/proc

exec switch_root /root /sbin/init